[tool.poetry]
name = "DSCI_524_Group_5"
version = "0.0.0"
description = "DSCI_524 Package"
authors = ["Rowan Sivanandam"]
license = "None"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
