name: ci-cd

on: [push, pull_request]

jobs:
  ci:
    # Step 1. Set up operating system
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    # Step 2. Set up Python 3.9
    - uses: actions/setup-python@v1
      with:
        python-version: 3.9
    # Step 3. Check-out repository so we can access its contents
    - uses: actions/checkout@v1
    # Step 4. Install poetry
    - uses: snok/install-poetry@v1
    # Step 5. Install our package
    - name: Install package
      run: poetry install
    # Step 6. Run tests for package
    - name: Test python
      run: python -c"import EDAhelper"

